/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_wangbaiyuan_byblog_jni_BYJNI */

#ifndef _Included_cn_wangbaiyuan_byblog_jni_BYJNI
#define _Included_cn_wangbaiyuan_byblog_jni_BYJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_wangbaiyuan_byblog_jni_BYJNI
 * Method:    getHOMEURL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_wangbaiyuan_byblog_jni_BYJNI_getHOMEURL
        (JNIEnv *, jobject);

/*
 * Class:     cn_wangbaiyuan_byblog_jni_BYJNI
 * Method:    getAPPLINK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_wangbaiyuan_byblog_jni_BYJNI_getAPPLINK
        (JNIEnv *, jobject);

/*
 * Class:     cn_wangbaiyuan_byblog_jni_BYJNI
 * Method:    getAPIURL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_wangbaiyuan_byblog_jni_BYJNI_getAPIURL
        (JNIEnv *, jobject);

/*
 * Class:     cn_wangbaiyuan_byblog_jni_BYJNI
 * Method:    getBAIDU_PUSH_API_KEY
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_wangbaiyuan_byblog_jni_BYJNI_getBAIDU_1PUSH_1API_1KEY
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
